### PR TITLE
Gradle: Fix prev built module "leaking" files into subsequent build

### PR DESCRIPTION
**Pull request by antonio-tomac**
Same as #119 but for `jib-layer-filter-extension-gradle`

### CODE REVIEW

**Review by elefeint — APPROVED** [review]
Thank you very much!

**Comment by antonio-tomac** [comment]
@elefeint @chanseokoh 
Is there any change to have release `v0.2.1` in the near future?
As fas as I can see all changes between `v0.2.0` and current `master` is minor refactoring, code style, documentation and my bug-fix. Diff: https://github.com/GoogleContainerTools/jib-extensions/compare/v0.2.0-jib-layer-filter-extension-maven...master

**Comment by elefeint** [comment]
We will release next week.

**Comment by elefeint** [comment]
`jib-layer-filter-extension-gradle:v0.3.0` released.

**Pull request merged**
