### PR TITLE
update jib-core version to 0.22.0 and plugins versions to 3.3.0

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Comment by emmileaf** [comment]
Would it usually take a bit of time for the new releases to get updated in the Maven Repository?

**Comment by mpeddada1** [comment]
Hm I was also wondering that. It usually takes a couple of hours to upload. I see that 3.3.0 is available at https://plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/ and https://plugins.gradle.org/plugin/com.google.cloud.tools.jib but not at https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/

**Comment by chanseokoh** [comment]
Removing `gradle.plugin.` works, but no idea why.

```diff
-    JIB_GRADLE: 'gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.0',
+    JIB_GRADLE: 'com.google.cloud.tools:jib-gradle-plugin:3.3.0',
```

**Comment by mpeddada1** [comment]
oh good observation, thanks Chanseok! Will try with removing the `gradle.plugin`. Interesting that it worked fine in the past- I wonder what changed.

**Comment by elefeint** [comment]
Gradle in core Jib got upgraded from 6.0.1 to 6.6.1 in https://github.com/GoogleContainerTools/jib/pull/3670 . Could this have caused publishing to be done without the prefix?

**Comment by mpeddada1** [comment]
That does seem like a likely cause! Which also reminds me, maybe we should upgrade the gradle version here to be consistent with the main Jib repo?

**Review by elefeint — APPROVED** [review]

**Comment by mpeddada1** [comment]
Afaik it may not have a major impact on how jib is configured. Our [README instructions](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#setup) specify jib to applied the following way: `plugins { id 'com.google.cloud.tools.jib' version '3.3.0'}` and our examples also follow the same pattern. Additionally, `com.google.cloud.tools:jib-gradle-plugin:3.3.0` is a compile-time dependency in jib-extensions and is only used to access certain jib-gradle classes in the extensions where it is applied.

**Comment by mpeddada1** [comment]
Oh actually looking at @chanseokoh's comment, there may be a couple of cases: https://github.com/GoogleContainerTools/jib/issues/3719#issuecomment-1234595127

**Comment by chanseokoh** [comment]
It will be pretty rare, as it mostly for those who want to use the jib-gradle-plugin JAR as a library (for whatever weird reasons) rather than using the Jib plugin in a Gradle build. It's not the use case we really support.

**Comment by elefeint** [comment]
Sounds good; not breaking the documented usecases then.

**Pull request merged**
