### PR TITLE
Update README with instructions for Quarkus fast-jar support

### PR DESCRIPTION
**Pull request by zanmagerl**
As discussed in  #129 this is the PR with documentation updates that show the possibility of using the fast-jar package type.

### CODE REVIEW

**Review by elefeint — APPROVED** [review]
Thank you! Great docs, and extra typo fixes, too...

**Comment by zanmagerl** [comment]
Can I just ask, when it is planned to release a new version of this Quarkus jib extension?

**Comment by elefeint** [comment]
Yes, sorry. We are planning to release Jib with extensions in the second half of August.

**Comment by zanmagerl** [comment]
Great, thank you for the info! 👍

**Pull request merged**
